=== aanzieu/42-Raytracing/gpu/testfiles/norme.dtd
<!ELEMENT scene (camera|light|ambient|sphere|plane|cylinder|disk|cone|paraboloid|hyperboloid|mobius)*>
<!ELEMENT camera (pos, dir, rot*, tra*)>
<!ELEMENT light (pos, dir*, color*, intensity)>
<!ELEMENT ambient (color, intensity)>
<!ELEMENT plane (origin, normal, tra*, rot*, color, reflection*)>
<!ELEMENT sphere (pos, tra*, radius, color, reflection*)>
<!ELEMENT mobius (pos, tra*, radius, color, reflection*)>
<!ELEMENT cylinder (pos, normal, radius, rot*, color, reflection*)>
<!ELEMENT disk (origin, normal, radius, rot*, color, reflection*)>
<!ELEMENT cone (pos, normal, radius, height, min*, max*, rot*, color, reflection*)>
<!ELEMENT paraboloid (top, normal, radius, height, rot*, color, reflection*)>
<!ELEMENT hyperboloid (top, normal, radius, height, rot*, color, reflection*)>


<!ELEMENT pos (#PCDATA)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT rot (#PCDATA)>
<!ELEMENT tra (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT origin (#PCDATA)>
<!ELEMENT normal (#PCDATA)>
<!ELEMENT radius (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT intensity (#PCDATA)>
<!ELEMENT reflection (#PCDATA)>


<!ATTLIST scene name CDATA #REQUIRED>
<!ATTLIST pos
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST dir
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST rot
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST tra
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST top
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST min
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST max
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST origin
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST normal
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST color
	r CDATA #REQUIRED
	g CDATA #REQUIRED
	b CDATA #REQUIRED
	a CDATA #REQUIRED
>
<!ATTLIST radius data CDATA #REQUIRED>
<!ATTLIST height data CDATA #REQUIRED>
<!ATTLIST intensity data CDATA #REQUIRED>
<!ATTLIST reflection data CDATA #REQUIRED>

=== aanzieu/42-Raytracing/testfiles/moebius.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "../dtd/norme.dtd">
<scene name="Test 1">

<camera>
	<pos x="-2" y="2" z="-50" />
	<dir x="3" y="2" z="1" />
	<rot x="0" y="0" z="0" />
	<tra x="0" y="0" z="0" />
</camera>
<ambient>
	<color r="255" g="255" b="255"/>
	<color r="255" g="255" b="255" a="1" />
	<intensity data="0.1" />
</ambient>
<light>
	<pos x="-3" y="-2" z="-4" />
	<color r="255" g="255" b="255"/>
	<color r="255" g="255" b="255" a="1" />
	<intensity data="1" />
</light>
<light>
	<pos x="1" y="1" z="-3" />
	<color r="255" g="255" b="255"/>
	<color r="255" g="255" b="255" a="0" />
	<intensity data="1" />
</light>
<light>
	<pos x="-1" y="1" z="-3" />
	<color r="255" g="255" b="255"/>
	<color r="255" g="255" b="255" a="0" />
	<intensity data="1" />
</light>
<mobius>
	<pos x="0" y="0" z="3" />
	<radius data="0.8" />
	<tra x="0" y="0" z="0" />
	<color r="255" g="0" b="0"/>
	<color r="255" g="0" b="0" a="1" />
	<reflection data="0.5" />
</mobius>
<plane>
	<origin x="0" y="-2" z="0" />
	<normal x="0" y="1" z="0" />
	<rot x="0" y="0" z="0" />
	<color r="123" g="123" b="200"/>
	<color r="123" g="123" b="200" a="0" />
	<reflection data="0" />
</plane>
</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/cone.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="Just a cone">
<camera>
	<pos x="0" y="0" z="-10" />
	<dir x="0" y="0" z="1" />
	<rot x="0" y="0" z="0" />
	<tra x="0" y="0" z="0" />
</camera>
<ambient>
	<color r="255" g="255" b="255" a="1" />
	<intensity data="0.1" />
</ambient>
<light>
	<pos x="-3" y="-2" z="-4" />
	<color r="255" g="255" b="255" a="1" />
	<intensity data="1" />
</light>
<cone>
	<pos x="0" y="-0.5" z="1" />
	<normal x="0" y="-2" z="1" />
	<radius data="0.4" />
	<height data="2" />
	<rot x="0" y="0" z="0" />
	<color r="12" g="24" b="255" a="1" />
	<reflection data="0.5" />
</cone>
</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="Cool gallery">
  <plane>
    <origin x="0" y="0.750000" z="1.000000"/>
    <normal x="0" y="0" z="1.000000"/>
    <color r="255" g="255" b="255"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </plane>
  <plane>
    <origin x="0" y="-0.750000" z="1.000000"/>
    <normal x="0" y="0" z="1.000000"/>
    <color r="151" g="20" b="42"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </plane>
  <plane>
    <origin x="0" y="0" z="2.000000"/>
    <normal x="0" y="0" z="1.000000"/>
    <color r="125" g="0" b="125"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </plane>
  <sphere>
    <pos x="0.750000" y="0.750000" z="0.500000"/>
    <radius data="0.200000"/>
    <color r="236" g="205" b="62"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </sphere>
  <sphere>
    <pos x="-0.750000" y="0.750000" z="0.500000"/>
    <radius data="0.200000"/>
    <color r="236" g="205" b="62"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </sphere>
  <sphere>
    <pos x="1.000000" y="0.750000" z="-0.500000"/>
    <radius data="0.200000"/>
    <color r="236" g="205" b="62"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </sphere>
  <sphere>
    <pos x="-1.000000" y="0.750000" z="-0.500000"/>
    <radius data="0.200000"/>
    <color r="236" g="205" b="62"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </sphere>
  <sphere>
    <pos x="0.750000" y="-0.750000" z="0.500000"/>
    <radius data="0.200000"/>
    <color r="236" g="205" b="62"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </sphere>
  <sphere>
    <pos x="-0.750000" y="-0.750000" z="0.500000"/>
    <radius data="0.200000"/>
    <color r="236" g="205" b="62"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </sphere>
  <sphere>
    <pos x="1.000000" y="-0.750000" z="-0.500000"/>
    <radius data="0.200000"/>
    <color r="236" g="205" b="62"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </sphere>
  <sphere>
    <pos x="0" y="0" z="0"/>
    <radius data="0.200000"/>
    <color r="255" g="0" b="0"/>
    <reflection data="1.000000"/>
    <refraction data="1.500000"/>
  </sphere>
  <cylinder>
    <pos x="-0.750000" y="0" z="0.500000"/>
    <normal x="0" y="1.000000" z="0"/>
    <radius data="0.100000"/>
    <color r="151" g="20" b="42"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </cylinder>
  <cylinder>
    <pos x="0.750000" y="0" z="0.500000"/>
    <normal x="0" y="1.000000" z="0"/>
    <radius data="0.100000"/>
    <color r="151" g="20" b="42"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </cylinder>
  <cylinder>
    <pos x="-1.000000" y="0" z="-0.500000"/>
    <normal x="0" y="1.000000" z="0"/>
    <radius data="0.100000"/>
    <color r="151" g="20" b="42"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </cylinder>
  <cylinder>
    <pos x="1.000000" y="0" z="-0.500000"/>
    <normal x="0" y="1.000000" z="0"/>
    <radius data="0.100000"/>
    <color r="151" g="20" b="42"/>
    <reflection data="0"/>
    <refraction data="1.000000"/>
  </cylinder>
  <light>
    <pos x="0" y="0" z="-2.000000"/>
    <color r="255" g="255" b="255"/>
    <intensity data="1.000000"/>
    <type data="POINT"/>
  </light>
  <light>
    <pos x="-2.000000" y="0" z="-5.000000"/>
    <color r="255" g="255" b="255"/>
    <intensity data="1.000000"/>
    <type data="POINT"/>
  </light>
  <ambient>
    <color r="255" g="255" b="255"/>
    <intensity data="0.400000"/>
  </ambient>
  <camera>
    <pos x="0" y="0" z="-10.000000"/>
    <dir x="0" y="0" z="1.000000"/>
  </camera>
</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/test1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="Test 1">

<camera>
  <pos x="-1" y="0" z="-10" />
  <dir x="0" y="0" z="1" />
  <!-- <tra x="-1" y="0" z="0" /> -->
</camera>

<light>
	<pos x="0" y="1" z="0" />
	<color r="255" g="255" b="255" />
	<intensity data="1" />
</light>

<light>
	<pos x="2" y="1" z="-3" />
	<color r="255" g="255" b="255" />
	<intensity data="1" />
</light>

<sphere>
	<pos x="-0.5" y="0" z="0.5" />
	<tra x="0" y="0" z="0" />
	<radius data="0.8" />
	<color r="255" g="255" b="255" />
	<reflection data="1" />
</sphere>

<plane>
	<origin x="0" y="-1" z="0" />
	<normal x="0" y="1" z="0" />
	<rot x="0" y="0" z="0" />
	<color r="123" g="123" b="200" />
	<reflection data="1" />
</plane>

<plane>
	<origin x="-2" y="0" z="0" />
	<normal x="-3" y="0" z="0" />
	<rot x="0" y="0" z="0" />
	<color r="0" g="255" b="255" />
	<reflection data="0" />
</plane>

<cone>
	<pos x="-0.5" y="0" z="0.5" />
	<normal x="-0.75" y="1" z="0.5" />
	<radius data="0.2" />
	<height data="2" />
	<color r="0" g="0" b="255" />
	<reflection data="1" />
</cone>

<!-- <plane>
	<origin x="1" y="1" z="0" />
	<normal x="-1" y="-1" z="-1" />
	<rot x="0" y="0" z="0" />
	<color r="0" g="255" b="0" />
	<reflection data="0.5" />
</plane> -->


</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/cylindre.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="Just a cylinder">
<camera>
	<pos x="0" y="0" z="-10" />
	<dir x="0" y="0" z="1" />
</camera>
<ambient>
	<color r="255" g="255" b="255" />
	<intensity data="0.1" />
</ambient>
<light>
	<pos x="0.5" y="0.5" z="-5" />
	<color r="255" g="255" b="255" />
	<intensity data="0.5" />
</light>

<light>
	<pos x="0" y="0.2" z="-5" />
	<color r="100" g="100" b="100" />
	<intensity data="0.4" />
</light>

<light>
	<pos x="-0.5" y="0.5" z="-3" />
	<color r="255" g="255" b="255" />
	<intensity data="0.5" />
</light>

<cylinder>
	<pos x="0" y="0" z="3" />
	<normal x="0" y="1" z="3" />
	<radius data="0.4" />
	<rot x="0" y="0" z="0" />
	<color r="255" g="125" b="255" />
	<reflection data="0" />
</cylinder>
<plane>
	<origin x="0" y="-1" z="0" />
	<normal x="0" y="1" z="0" />
	<rot x="0" y="0" z="0" />
	<color r="123" g="123" b="200" />
	<reflection data="0" />
</plane>
</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/torus.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="2 Spheres">

<camera>
  <pos x="-0.5" y="0" z="-1.1" />
  <dir x="0" y="3" z="1" />
  <rot x="0" y="0" z="0" />
  <tra x="0" y="4.5" z="0" />
</camera>

<light>
  <pos x="0" y="0" z="-5" />
  <dir x="0" y="0" z="1" />
  <color r="255" g="255" b="255" a="1" />
  <intensity data="1" />
</light>

<ambient>
  <color r="255" g="255" b="255" a="1" />
  <intensity data="0.3" />
</ambient>

<plane>
  <origin x="0" y="-2" z="0" />
  <normal x="0" y="-1" z="0" />
  <rot x="0" y="10" z="0" />
  <color r="255" g="255" b="255" a="1" />
  <chess r="0" g="0" b="0"/>
  <reflection data="0" />
</plane>

<torus>
  <pos x="1" y="0" z="5" />
  <radius_small data="0.5" />
  <radius_big data="1" />
  <color r="84" g="133" b="64" a="1" />
  <chess r="0" g="0" b="0"/>
</torus>

</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/france.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="France's flag">

<ambient>
	<color r="255" g="255" b="255" />
	<intensity data="0.5" />
</ambient>

<camera>
	<pos x="5" y="0.3" z="-10" />
	<dir x="0" y="0" z="1" />
</camera>

<light>
	<pos x="0.5" y="0.5" z="-5" />
	<color r="255" g="255" b="255" />
	<intensity data="0.5" />
</light>

<light>
	<pos x="0" y="0.2" z="-5" />
	<color r="100" g="100" b="100" />
	<intensity data="0.4" />
</light>

<light>
	<pos x="-0.5" y="0.5" z="-3" />
	<color r="255" g="255" b="255" />
	<intensity data="0.5" />
</light>

<!--Blue stripe-->

<sphere>
	<pos x="0" y="0" z="1" />
	<radius data="0.4" />
	<color r="50" g="50" b="255" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="0" y="0.3" z="1" />
	<radius data="0.4" />
	<color r="50" g="50" b="255" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="0" y="0.6" z="1" />
	<radius data="0.4" />
	<color r="50" g="50" b="255" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="0" y="0.9" z="1" />
	<radius data="0.4" />
	<color r="50" g="50" b="255" />
	<reflection data="0" />
</sphere>

<!---->

<!--White stripe-->

<sphere>
	<pos x="0.5" y="0" z="1" />
	<radius data="0.4" />
	<color r="255" g="255" b="255" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="0.5" y="0.3" z="1" />
	<radius data="0.4" />
	<color r="255" g="255" b="255" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="0.5" y="0.6" z="1" />
	<radius data="0.4" />
	<color r="255" g="255" b="255" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="0.5" y="0.9" z="1" />
	<radius data="0.4" />
	<color r="255" g="255" b="255" />
	<reflection data="0" />
</sphere>

<!---->

<!--Red stripe-->

<sphere>
	<pos x="1" y="0" z="1" />
	<radius data="0.4" />
	<color r="255" g="30" b="20" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="1" y="0.3" z="1" />
	<radius data="0.4" />
	<color r="255" g="30" b="20" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="1" y="0.6" z="1" />
	<radius data="0.4" />
	<color r="255" g="30" b="20" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="1" y="0.9" z="1" />
	<radius data="0.4" />
	<color r="255" g="30" b="20" />
	<reflection data="0" />
</sphere>

<!---->

<plane>
	<origin x="0" y="-1" z="0" />
	<normal x="0" y="1" z="0" />
	<rot x="0" y="0" z="0" />
	<color r="123" g="123" b="200" />
	<reflection data="0" />
</plane>

</scene>

=== aanzieu/42-Raytracing/gpu/scenes/2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "../dtd/norme.dtd">
<scene name="3 Spheres">
<camera>
  <pos x="-7.800000" y="3" z="-20.1" />
  <dir x="0.347532" y="-0.054830" z="0.922895" />
  <rot x="0" y="0" z="0" />
  <tra x="0" y="0" z="0" />
</camera>

<light>
  <pos x="-2" y="0" z="-5" />
  <dir x="0" y="-1" z="0" />
  <color r="103" g="104" b="83" />
  <intensity data="0.3" />
</light>
<light>
  <pos x="0" y="0" z="5" />
  <dir x="0" y="0" z="1" />
  <color r="104" g="165" b="143" />
  <intensity data="0.7" />
</light>
<ambient>
  <color r="255" g="255" b="255" />
  <intensity data="0.4" />
</ambient>
<plane>
  <origin x="0" y="-1" z="0" />
  <normal x="0" y="1" z="0" />
  <rot x="0" y="0" z="0" />
  <color r="255" g="255" b="255" />
  <chess r="0" g="0" b="0" />
  <reflection data="0.999999" />
</plane>
<sphere>
  <pos x="0.8" y="0" z="0" />
  <radius data="2" />
  <color r="64" g="164" b="114" />
  <reflection data="0.7" />
</sphere>
<sphere>
  <pos x="5.5" y="0" z="3.5" />
  <radius data="1" />
  <color r="194" g="90" b="79" />
  <refraction data="0.5" />
</sphere>
<sphere>
  <pos x="-2.2" y="0" z="2.2" />
  <radius data="1" />
  <color r="138" g="105" b="100" />
  <refraction data="0.325" />
</sphere>
 <sphere>
  <pos x="0.8" y="0" z="0" />
  <radius data="1" />
  <color r="205" g="255" b="205" />
   <reflection data="0.7" />
 </sphere>
</scene>
