=== aanzieu/42-Raytracing/gpu/testfiles/norme.dtd
<!ELEMENT scene (camera|light|ambient|sphere|plane|cylinder|disk|cone|paraboloid|hyperboloid|mobius)*>
<!ELEMENT camera (pos, dir, rot*, tra*)>
<!ELEMENT light (pos, dir*, color*, intensity)>
<!ELEMENT ambient (color, intensity)>
<!ELEMENT plane (origin, normal, tra*, rot*, color, reflection*)>
<!ELEMENT sphere (pos, tra*, radius, color, reflection*)>
<!ELEMENT mobius (pos, tra*, radius, color, reflection*)>
<!ELEMENT cylinder (pos, normal, radius, rot*, color, reflection*)>
<!ELEMENT disk (origin, normal, radius, rot*, color, reflection*)>
<!ELEMENT cone (pos, normal, radius, height, min*, max*, rot*, color, reflection*)>
<!ELEMENT paraboloid (top, normal, radius, height, rot*, color, reflection*)>
<!ELEMENT hyperboloid (top, normal, radius, height, rot*, color, reflection*)>


<!ELEMENT pos (#PCDATA)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT rot (#PCDATA)>
<!ELEMENT tra (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT origin (#PCDATA)>
<!ELEMENT normal (#PCDATA)>
<!ELEMENT radius (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT intensity (#PCDATA)>
<!ELEMENT reflection (#PCDATA)>


<!ATTLIST scene name CDATA #REQUIRED>
<!ATTLIST pos
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST dir
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST rot
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST tra
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST top
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST min
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST max
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST origin
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST normal
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST color
	r CDATA #REQUIRED
	g CDATA #REQUIRED
	b CDATA #REQUIRED
	a CDATA #REQUIRED
>
<!ATTLIST radius data CDATA #REQUIRED>
<!ATTLIST height data CDATA #REQUIRED>
<!ATTLIST intensity data CDATA #REQUIRED>
<!ATTLIST reflection data CDATA #REQUIRED>

=== aanzieu/42-Raytracing/gpu/testfiles/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="France's flag">
  <plane>
    <origin x="0" y="-1.000000" z="0"/>
    <normal x="0" y="1.000000" z="0"/>
    <color r="123" g="123" b="200"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </plane>
   <sphere>
    <pos x="1" y="0" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="50" g="50" b="255"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere> 
   <sphere>
    <pos x="0" y="0.300000" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="50" g="50" b="255"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <sphere>
    <pos x="0" y="0.600000" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="50" g="50" b="255"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere> 
  <sphere>
    <pos x="0" y="0.900000" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="50" g="50" b="255"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <sphere>
    <pos x="0.500000" y="0" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="255" g="255" b="255"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <sphere>
    <pos x="0.500000" y="0.300000" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="255" g="255" b="255"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <sphere>
    <pos x="0.500000" y="0.600000" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="255" g="255" b="255"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <sphere>
    <pos x="0.500000" y="0.900000" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="255" g="255" b="255"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <sphere>
    <pos x="1.000000" y="0" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="255" g="30" b="20"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <sphere>
    <pos x="1.000000" y="0.300000" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="255" g="30" b="20"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <sphere>
    <pos x="1.000000" y="0.600000" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="255" g="30" b="20"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <sphere>
    <pos x="1.000000" y="0.900000" z="1.000000"/>
    <radius data="0.400000"/>
    <color r="255" g="30" b="20"/>
    <reflection data="0"/>
    <refraction data="1"/>
  </sphere>
  <light>
    <pos x="0.500000" y="0.500000" z="-5.000000"/>
    <color r="255" g="255" b="255"/>
    <intensity data="0.500000"/>
  </light>
  <light>
    <pos x="0" y="0.200000" z="-5.000000"/>
    <color r="100" g="100" b="100"/>
    <intensity data="0.400000"/>
  </light>
  <light>
    <pos x="-0.500000" y="0.500000" z="-3.000000"/>
    <color r="255" g="255" b="255"/>
    <intensity data="0.500000"/>
  </light>
  <ambient>
    <color r="255" g="255" b="255"/>
    <intensity data="0.500000"/>
  </ambient>
  <camera>
    <pos x="5.000000" y="0.300000" z="-10.000000"/>
    <dir x="0" y="0" z="1.000000"/>
  </camera>
</scene>

=== aanzieu/42-Raytracing/scenes/new.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "../dtd/norme.dtd">
<scene name="new file">
  <plane>
    <origin x="0" y="-1.000000" z="0"/>
    <normal x="0" y="1.000000" z="0"/>
    <color r="163" g="163" b="163"/>
    <reflection data="0"/>
    <refraction data="0"/>
  </plane>
  <light>
    <pos x="0" y="30.000000" z="-30.000000"/>
    <dir x="0" y="0.000000" z="-30.000000"/>
    <color r="255" g="255" b="255"/>
    <intensity data="0.699999"/>
    <type data="POINT"/>
  </light>
  <ambient>
    <color r="255" g="255" b="255"/>
    <intensity data="0.200000"/>
  </ambient>
  <camera>
    <pos x="0" y="0" z="-12.000000"/>
    <dir x="0" y="0" z="1.000000"/>
  </camera>
</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name=" file">
  <plane>
    <origin x="0" y="-1.000000" z="0"/>
    <normal x="0" y="1.000000" z="0"/>
    <color r="236" g="205" b="62"/>
    <chess r="0" g="0" b="0"/>
    <reflection data="0.500000"/>
    <refraction data="0"/>
  </plane>
  <sphere>
    <pos x="0" y="2.800000" z="-1.600000"/>
    <radius data="1.200000"/>
    <color r="168" g="168" b="168"/>
    <reflection data="1.000000"/>
    <refraction data="0"/>
  </sphere>
  <sphere>
    <pos x="-0.400000" y="3.000000" z="-2.700000"/>
    <radius data="0.200000"/>
    <color r="245" g="246" b="245"/>
    <reflection data="0"/>
    <refraction data="1.500000"/>
  </sphere>
  <sphere>
    <pos x="0.400000" y="3.000000" z="-2.700000"/>
    <radius data="0.200000"/>
    <color r="248" g="248" b="247"/>
    <reflection data="0"/>
    <refraction data="1.500000"/>
  </sphere>
  <paraboloid>
    <top x="-1.600000" y="0.500000" z="-1.700000"/>
    <normal x="0" y="-1.000000" z="-0.200000"/>
    <radius data="0.020000"/>
    <height data="0.100000"/>
    <color r="205" g="168" b="0"/>
    <reflection data="1.000000"/>
    <refraction data="0"/>
  </paraboloid>
  <paraboloid>
    <top x="1.600000" y="0.500000" z="-1.700000"/>
    <normal x="0" y="-1.000000" z="-0.200000"/>
    <radius data="0.020000"/>
    <height data="-0.100000"/>
    <color r="205" g="168" b="0"/>
    <reflection data="1.000000"/>
    <refraction data="0"/>
  </paraboloid>
  <light>
    <pos x="0" y="0" z="-8.000000"/>
    <color r="255" g="255" b="255"/>
    <intensity data="0.800000"/>
  </light>
  <light>
    <pos x="0" y="0" z="0"/>
    <color r="255" g="255" b="255"/>
    <intensity data="0.100000"/>
  </light>
  <ambient>
    <color r="255" g="255" b="255"/>
    <intensity data="0.400000"/>
  </ambient>
  <camera>
    <pos x="15.000000" y="1.000000" z="-20.000000"/>
    <dir x="-1.000000" y="1.000000" z="1.000000"/>
  </camera>
</scene>

=== aanzieu/42-Raytracing/testfiles/good2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "../dtd/norme.dtd">
<scene name="2 Spheres">

<camera>
  <pos x="0" y="0" z="-3" />
  <dir x="0" y="0" z="1" />
  <rot x="0" y="0" z="0" />
  <tra x="0" y="0" z="0" />
</camera>
<ambient>

  <color r="255" g="255" b="255" />
  <intensity data="1" />
</ambient>
<light>
  <pos x="0" y="0" z="-2" />
  <dir x="0" y="2" z="1" />
  <color r="255" g="255" b="255" />
  <intensity data="1" />
</light>

<!--light>
  <pos x="0" y="0" z="5" />
  <dir x="0" y="0" z="1" />
  <color r="255" g="255" b="255" a="0.5" />
  <intensity data="1" />
</light-->

<ambient>
  <color r="255" g="255" b="255" />
  <intensity data="0.4" />
</ambient>

<plane>
  <origin x="0" y="-1" z="0" />
  <normal x="0" y="1" z="0" />
  <rot x="0" y="0" z="0" />
  <color r="255" g="255" b="255" />
  <chess r="0" g="0" b="0" />
  <reflection data="0" />
</plane>

<!--sphere>
  <pos x="0.5" y="0.5" z="1" />
  <radius data="0.4" />
  <color r="20" g="20" b="120" />
  <transparence data="0.90" />
</sphere>-->

<cone>
  <pos x="-0.5" y="0" z="0" />
  <normal x="0" y="1" z="0" />
  <radius data="0.35" />
  <height data="0.5" />
  <color r="0" g="255" b="0" />
  <reflection data="0" />
</cone>

<!-- <triangle>
  <pos x="0" y="0" z="0" />
  <normal x="1" y="0" z="0" />
  <v1 x="0" y="1.2" z="0" />
  <v2 x="1" y="1.2" z="0" />
  <color r="1" g="0" b="255" a="1" />
  <reflection data="1" />
</triangle> -->

<!-- <cone>
  <pos x="1" y="0.3" z="0" />
  <normal x="1" y="1.3" z="-0.3" />
  <radius data="0.45" />
  <height data="0.5" />
  <color r="0" g="255" b="0" a="1" />
</cone> -->

<!-- <light>
     <pos x="0" y="4" z="0" />
     <dir x="1" y="0" z="0" />
     <color r="0" g="255" b="50" a="1" />
     <intensity data="0.3" />
</light> -->

<!-- <ambient>
     <color r="0" g="255" b="50" a="1" />
     <intensity data="0.4" />
</ambient> -->

<!-- <disk>
     <origin x="0" y="-1" z="2" />
     <normal x="0" y="0" z="2" />
     <radius data="1" />
     <rot x="0" y="0" z="0" />
     <color r="0" g="255" b="0" a="1" />
</disk>

<disk>
  <origin x="-0.5" y="-0.5" z="2" />
  <normal x="0" y="0" z="2" />
  <radius data="0.5" />
  <rot x="0" y="0" z="0" />
  <color r="0" g="0" b="255" a="1" />
</disk> -->
<!-- <paraboloid>
     <top x="0" y="0" z="0" />
     <normal x="0" y="1" z="1" />
     <radius data="0.2" />
     <height data="1" />
     <color r="255" g="0" b="0" a="1" />
</paraboloid> -->

<!-- <hyperboloid>
     <top x="0" y="0" z="0" />
     <normal x="0" y="1" z="0" />
     <radius data="0.2" />
     <height data="1" />
     <color r="0" g="255" b="0" a="1" />
</hyperboloid> -->

</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/new.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="Empty file">

<camera>
  <pos x="0" y="0" z="-20" />
  <dir x="0" y="0" z="1" />
  <rot x="0" y="0" z="0" />
  <tra x="0" y="0" z="0" />
</camera>

<light>
  <pos x="0" y="0" z="-2" />
  <dir x="0" y="2" z="1" />
  <color r="255" g="255" b="255" />
  <intensity data="1" />
</light>

<ambient>
  <color r="255" g="255" b="255" />
  <intensity data="0.4" />
</ambient>

</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/moebius.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="Test 1">

<camera>
	<pos x="-5" y="1" z="-50" />
	<dir x="0" y="0" z="3" />
</camera>
<ambient>
	<color r="255" g="255" b="255" a="1" />
	<intensity data="0.1" />
</ambient>

<mobius>
	<pos x="0" y="0" z="3" />
	<tra x="0" y="0" z="0" />
	<radius data="0.8" />
	<color r="255" g="0" b="0" a="1" />
	<reflection data="0.5" />
</mobius>
<plane>
	<origin x="0" y="-2" z="0" />
	<normal x="0" y="1" z="0" />
	<rot x="0" y="0" z="0" />
	<color r="123" g="123" b="200" a="0" />
	<reflection data="0" />
</plane>
<light>
	<pos x="1" y="1" z="-3" />
	<color r="255" g="255" b="255" a="0" />
	<intensity data="1" />
</light>
<light>
	<pos x="-1" y="1" z="-3" />
	<color r="255" g="255" b="255" a="0" />
	<intensity data="1" />
</light>
</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="BoxColor">
  <plane>
    <origin x="0" y="-1.300000" z="0"/>
    <normal x="0" y="1.000000" z="0"/>
    <color r="226" g="222" b="72"/>
    <reflection data="0.999998"/>
    <refraction data="1.200000"/>
  </plane>
  <plane>
    <origin x="-11.000000" y="0" z="0"/>
    <normal x="2.000000" y="0" z="0"/>
    <color r="216" g="38" b="38"/>
    <reflection data="1.000000"/>
    <refraction data="1.200000"/>
  </plane>
  <sphere>
    <pos x="-2.200000" y="1.000000" z="0"/>
    <radius data="2.000000"/>
    <color r="185" g="26" b="26"/>
    <reflection data="0.699999"/>
    <refraction data="0"/>
  </sphere>
  <sphere>
    <pos x="-5.500000" y="6.000000" z="3.500000"/>
    <radius data="1.000000"/>
    <color r="157" g="123" b="38"/>
    <reflection data="0"/>
    <refraction data="0.699999"/>
  </sphere>
  <sphere>
    <pos x="-6.200000" y="2.000000" z="2.200000"/>
    <radius data="1.000000"/>
    <color r="138" g="105" b="100"/>
    <reflection data="0"/>
    <refraction data="0.324999"/>
  </sphere>
  <cylinder>
    <pos x="-13.900000" y="-1.000000" z="0"/>
    <normal x="0.899999" y="1.600000" z="0"/>
    <radius data="0.500000"/>
    <color r="211" g="229" b="25"/>
    <reflection data="0.200000"/>
    <refraction data="0"/>
  </cylinder>
  <cone>
    <pos x="-8.000000" y="3.000000" z="-0.500000"/>
    <normal x="-8.601555" y="-1.877240" z="1.655057"/>
    <radius data="0.700000"/>
    <height data="1.600000"/>
    <min x="1.000000" y="1.000000" z="1.000000"/>
    <max x="3.000000" y="3.000000" z="3.000000"/>
    <color r="224" g="127" b="11"/>
    <reflection data="0"/>
    <refraction data="0"/>
  </cone>
  <torus>
    <pos x="1.099999" y="4.899999" z="-3.300000"/>
    <radius_small data="0.600000"/>
    <radius_big data="1.100000"/>
    <color r="116" g="182" b="14"/>
    <reflection data="0.300000"/>
    <refraction data="0"/>
  </torus>
  <light>
    <pos x="-9.000000" y="10.000000" z="-3.000000"/>
    <color r="103" g="104" b="83"/>
    <intensity data="0.300000"/>
    <type data="POINT"/>
  </light>
  <light>
    <pos x="3" y="2" z="5.000000"/>
    <color r="104" g="165" b="143"/>
    <intensity data="0.700000"/>
    <type data="POINT"/>
  </light>
  <ambient>
    <color r="255" g="255" b="255"/>
    <intensity data="0.400000"/>
  </ambient>
  <camera>
    <pos x="-7.000000" y="5.000000" z="-69.100000"/>
    <dir x="-7.652467" y="3.945170" z="-45.077105"/>
  </camera>
</scene>

=== aanzieu/42-Raytracing/testfiles/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "../dtd/norme.dtd">
<scene name="One sphere">

<camera>
	<pos x="-1" y="0.3" z="-10" />
	<dir x="0" y="0" z="1" />
	<!-- <tra x="-1" y="0" z="0" /> -->
</camera>

<light>
	<pos x="0.5" y="0.5" z="-5" />
	<color r="255" g="255" b="255" a="1" />
	<intensity data="0.5" />
</light>

<light>
	<pos x="0" y="0.2" z="-5" />
	<color r="100" g="100" b="100" a="1" />
	<intensity data="0.4" />
</light>

<light>
	<pos x="-0.5" y="0.5" z="-3" />
	<color r="255" g="255" b="255" a="1" />
	<intensity data="0.5" />
</light>

<sphere>
	<pos x="2" y="0" z="-3" />
	<radius data="0.4" />	
	<tra x="0" y="0" z="0" />
	<color r="255" g="125" b="255" a="1" />
	<reflection data="0" />
</sphere>

<sphere>
	<pos x="0.2" y="0" z="-2" />
	<radius data="0.5" />	
	<tra x="0" y="0" z="0" />
	<color r="255" g="125" b="255" a="1" />
	<!--<reflection data="-1" />    -->
	<refraction data="1.01" />	
</sphere>

<plane>
	<origin x="0" y="-1" z="0" />
	<normal x="0" y="1" z="0" />
	<rot x="0" y="0" z="0" />
	<color r="123" g="123" b="200" a="1" />
	<reflection data="0" />
</plane>

<plane>
	<origin x="0" y="0" z="2" />
	<normal x="0" y="0" z="-1" />
	<rot x="0" y="0" z="0" />
	<color r="123" g="123" b="200" a="1" />
	<reflection data="0" />
</plane>

<cylinder>
	<pos x="0.5" y="0" z="1" />
	<normal x="0.5" y="1" z="1" />
	<radius data="0.5" />
	<rot x="0" y="0" z="0" />
	<color r="151" g="20" b="42" a="1" />
</cylinder>

</scene>
