=== aanzieu/42-Raytracing/gpu/testfiles/norme.dtd
<!ELEMENT scene (camera|light|ambient|sphere|plane|cylinder|disk|cone|paraboloid|hyperboloid|mobius)*>
<!ELEMENT camera (pos, dir, rot*, tra*)>
<!ELEMENT light (pos, dir*, color*, intensity)>
<!ELEMENT ambient (color, intensity)>
<!ELEMENT plane (origin, normal, tra*, rot*, color, reflection*)>
<!ELEMENT sphere (pos, tra*, radius, color, reflection*)>
<!ELEMENT mobius (pos, tra*, radius, color, reflection*)>
<!ELEMENT cylinder (pos, normal, radius, rot*, color, reflection*)>
<!ELEMENT disk (origin, normal, radius, rot*, color, reflection*)>
<!ELEMENT cone (pos, normal, radius, height, min*, max*, rot*, color, reflection*)>
<!ELEMENT paraboloid (top, normal, radius, height, rot*, color, reflection*)>
<!ELEMENT hyperboloid (top, normal, radius, height, rot*, color, reflection*)>


<!ELEMENT pos (#PCDATA)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT rot (#PCDATA)>
<!ELEMENT tra (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT origin (#PCDATA)>
<!ELEMENT normal (#PCDATA)>
<!ELEMENT radius (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT intensity (#PCDATA)>
<!ELEMENT reflection (#PCDATA)>


<!ATTLIST scene name CDATA #REQUIRED>
<!ATTLIST pos
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST dir
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST rot
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST tra
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST top
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST min
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST max
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST origin
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST normal
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>
<!ATTLIST color
	r CDATA #REQUIRED
	g CDATA #REQUIRED
	b CDATA #REQUIRED
	a CDATA #REQUIRED
>
<!ATTLIST radius data CDATA #REQUIRED>
<!ATTLIST height data CDATA #REQUIRED>
<!ATTLIST intensity data CDATA #REQUIRED>
<!ATTLIST reflection data CDATA #REQUIRED>

=== aanzieu/42-Raytracing/gpu/testfiles/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="BoxColor">
  <plane>
    <origin x="6.299999" y="0" z="0"/>
    <normal x="-1.000000" y="0" z="0"/>
    <color r="231" g="4" b="4"/>
    <reflection data="1.000000"/>
    <refraction data="0"/>
  </plane>
  <plane>
    <origin x="-6.599999" y="0" z="0"/>
    <normal x="1.000000" y="0" z="0"/>
    <color r="30" g="193" b="152"/>
    <reflection data="1.000000"/>
    <refraction data="0"/>
  </plane>
  <plane>
    <origin x="0" y="3.000000" z="0"/>
    <normal x="0" y="1.000000" z="0"/>
    <color r="87" g="100" b="177"/>
    <reflection data="1.000000"/>
    <refraction data="0"/>
  </plane>
  <plane>
    <origin x="0" y="0" z="20.000000"/>
    <normal x="0" y="0" z="-1.000000"/>
    <color r="236" g="205" b="62"/>
    <reflection data="1.000000"/>
    <refraction data="0"/>
  </plane>
  <plane>
    <origin x="0" y="-3.000000" z="0"/>
    <normal x="0" y="1.000000" z="0"/>
    <color r="105" g="213" b="59"/>
    <reflection data="1.000000"/>
    <refraction data="0"/>
  </plane>
  <sphere>
    <pos x="-4.000000" y="0" z="17.500000"/>
    <radius data="1.500000"/>
    <color r="19" g="126" b="34"/>
    <reflection data="0"/>
    <refraction data="0"/>
  </sphere>
  <sphere>
    <pos x="3.000000" y="0" z="4.300000"/>
    <radius data="2.100000"/>
    <color r="236" g="54" b="12"/>
    <reflection data="0"/>
    <refraction data="0"/>
  </sphere>
  <sphere>
    <pos x="2.000000" y="-1.000000" z="-28.500000"/>
    <radius data="0.700000"/>
    <color r="100" g="193" b="14"/>
    <chess r="47" g="163" b="10"/>
    <reflection data="0"/>
    <refraction data="0"/>
  </sphere>
  <cylinder>
    <pos x="5.000000" y="-1.300000" z="4.000000"/>
    <normal x="-0.400000" y="0.200000" z="0"/>
    <radius data="0.500000"/>
    <color r="15" g="60" b="163"/>
    <reflection data="0"/>
    <refraction data="0"/>
  </cylinder>
  <cone>
    <pos x="2.000000" y="0" z="2.500000"/>
    <normal x="1.676582" y="0.637511" z="2.834193"/>
    <radius data="0.100000"/>
    <height data="0"/>
    <min x="1.000000" y="1.000000" z="1.000000"/>
    <max x="3.000000" y="3.000000" z="3.000000"/>
    <color r="226" g="16" b="92"/>
    <reflection data="0"/>
    <refraction data="0"/>
  </cone>
  <light>
    <pos x="5.000000" y="-2.299999" z="-24.000000"/>
    <color r="255" g="255" b="255"/>
    <intensity data="0.899999"/>
    <type data="POINT"/>
  </light>
  <light>
    <pos x="0" y="0" z="0"/>
    <color r="255" g="255" b="255"/>
    <intensity data="0.100000"/>
    <type data="POINT"/>
  </light>
  <light>
    <pos x="0" y="0" z="0"/>
    <color r="255" g="255" b="255"/>
    <intensity data="0.100000"/>
    <type data="POINT"/>
  </light>
  <ambient>
    <color r="255" g="255" b="255"/>
    <intensity data="0.200000"/>
  </ambient>
  <camera>
    <pos x="0" y="0" z="-50.000000"/>
    <dir x="0" y="0" z="1.000000"/>
  </camera>
</scene>

=== aanzieu/42-Raytracing/testfiles/good3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "../dtd/norme.dtd">
<scene name="2 Spheres">

<camera>
  <pos x="0" y="0" z="-10" />
  <dir x="0" y="0" z="1" />
  <rot x="0" y="0" z="0" />
  <tra x="0" y="0" z="0" />
</camera>

<light>
  <pos x="0" y="0" z="-3" />
  <dir x="0" y="2" z="1" />
  <color r="255" g="255" b="255" />
  <intensity data="1" />
</light>

<light>
  <pos x="0" y="0" z="5" />
  <dir x="0" y="0" z="1" />
  <color r="255" g="255" b="255" />
  <intensity data="1" />
</light>

<plane>
  <origin x="0" y="-1.5" z="0" />
  <normal x="0" y="-1" z="0" />
  <rot x="0" y="0" z="0" />
  <color r="255" g="255" b="255" />
  <chess r="0" g="0" b="0" />
  <reflection data="0" />
</plane>

<!-- <cylinder>
  <pos x="0" y="0" z="0" />
  <normal x="1" y="0" z="2.25" />
  <radius data="0.25" />
  <height data="1" />
  <color r="0" g="255" b="0" />
</cylinder> -->

<triangle>
  <pos x="0" y="0" z="0" />
  <normal x="1" y="0" z="0" />
  <v1 x="0" y="1.2" z="0" />
  <v2 x="1" y="1.2" z="0" />
  <color r="1" g="0" b="255" />
  <reflection data="0.5" />
</triangle>

<cone>
  <pos x="1" y="0.3" z="0" />
  <normal x="1" y="1.3" z="-0.3" />
  <radius data="0.45" />
  <height data="0.5" />
  <color r="0" g="255" b="0" />
</cone>

<!-- <light>
     <pos x="0" y="4" z="0" />
     <dir x="1" y="0" z="0" />
     <color r="0" g="255" b="50" />
     <intensity data="0.3" />
</light> -->

<!-- <ambient>
     <color r="0" g="255" b="50" />
     <intensity data="0.4" />
</ambient> -->

<!-- <disk>
     <origin x="0" y="-1" z="2" />
     <normal x="0" y="0" z="2" />
     <radius data="1" />
     <rot x="0" y="0" z="0" />
     <color r="0" g="255" b="0" />
</disk>

<disk>
  <origin x="-0.5" y="-0.5" z="2" />
  <normal x="0" y="0" z="2" />
  <radius data="0.5" />
  <rot x="0" y="0" z="0" />
  <color r="0" g="0" b="255" />
</disk> -->
<!-- <paraboloid>
     <top x="0" y="0" z="0" />
     <normal x="0" y="1" z="1" />
     <radius data="0.2" />
     <height data="1" />
     <color r="255" g="0" b="0" />
</paraboloid> -->

<!-- <hyperboloid>
     <top x="0" y="0" z="0" />
     <normal x="0" y="1" z="0" />
     <radius data="0.2" />
     <height data="1" />
     <color r="0" g="255" b="0" />
</hyperboloid> -->

</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/save.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name=" file">
  <disk>
    <origin x="0.300000" y="0" z="0"/>
    <normal x="0.400000" y="2.200000" z="0.500000"/>
    <radius data="0.400000"/>
    <color r="236" g="205" b="62"/>
    <reflection data="0"/>
    <refraction data="0"/>
  </disk>
  <light>
    <pos x="0" y="0" z="-2.000000"/>
    <color r="255" g="255" b="255"/>
    <intensity data="1.000000"/>
  </light>
  <ambient>
    <color r="255" g="255" b="255"/>
    <intensity data="0.400000"/>
  </ambient>
  <camera>
    <pos x="0" y="0" z="-20.000000"/>
    <dir x="0" y="0" z="1.000000"/>
  </camera>
</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/plane_direct_light.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="Just a plane">

<camera>
	<pos x="0" y="1" z="-5" />
	<dir x="0" y="1" z="1" />
</camera>

<ambient>
	<color r="100" g="100" b="100" a="1" />
	<intensity data="0" />
</ambient>

<plane>
	<origin x="0" y="-0.5" z="1" />
	<normal x="0" y="-2" z="1" />
	<rot x="0" y="0" z="0" />
	<color r="255" g="245" b="255" a="1" />
	<reflection data="0" />
</plane>

<light>
	<pos x="0" y="0" z="10" />
	<color r="255" g="255" b="255" a="1" />
	<intensity data="0.5" />
</light>

</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/good.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "norme.dtd">
<scene name="2 Spheres">

<camera>
	<pos x="0" y="0" z="-5" />
	<dir x="0" y="0" z="1" />
	<rot x="0" y="1" z="0" />
	<tra x="0.5" y="0" z="0" />
</camera>

<light>
	<pos x="0" y="-2" z="-2" />
	<dir x="1" y="0" z="1" />
	<color r="0" g="255" b="50" a="1" />
	<intensity data="1" />
</light>

<light>
	<pos x="0" y="2" z="-2" />
	<dir x="-2" y="0" z="0" />
	<color r="0" g="255" b="50" a="1" />
	<intensity data="0.3" />
</light>

<!-- <ambient>
	<color r="0" g="255" b="50" a="1" />
	<intensity data="0.1" />
</ambient> -->

<plane>
	<origin x="0" y="-1" z="1" />
	<normal x="0" y="-2" z="1" />
	<color r="255" g="255" b="255" a="1" />
	<reflection data="0" />
</plane>

<sphere>
	<pos x="-1" y="0" z="10" />
	<tra x="0" y="1" z="0" />
	<radius data="0.5" />
	<color r="255" g="255" b="255" a="1" />
	<reflection data="1" />
</sphere>

<sphere>
	<pos x="0" y="0" z="2" />
	<tra x="0" y="0" z="0" />
	<radius data="0.5" />
	<color r="255" g="255" b="255" a="1" />
	<reflection data="2" />
</sphere>

</scene>

=== aanzieu/42-Raytracing/gpu/testfiles/paraboloid.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "../dtd/norme.dtd">
<scene name="Just a Paraboloid">
<camera>
	<pos x="0" y="0" z="-10" />
	<dir x="0" y="0" z="1" />
	<rot x="0" y="0" z="0" />
	<tra x="0" y="0" z="0" />
</camera>
<ambient>
	<color r="255" g="255" b="255" />
	<intensity data="0.1" />
</ambient>
<light>
	<pos x="0" y="2" z="-5" />
	<color r="255" g="255" b="255" />
	<intensity data="1" />
</light>
<paraboloid>
	<top x="0" y="-1" z="5" />
	<normal x="0" y="3" z="5" />
	<radius data="0.1" />
	<height data="1" />
	<color r="0" g="102" b="255" />
	<reflection data="0" />
</paraboloid>

<!-- <hyperboloid>
	<top x="0" y="0" z="0" />
	<normal x="0" y="1" z="0" />
	<radius data="0.2" />
	<height data="1" />
	<color r="0" g="255" b="0" />
</hyperboloid> -->

<cylinder>
	<pos x="-1" y="0" z="-0.5" />
	<normal x="-1" y="1" z="-0.5" />
	<radius data="0.1" />
	<rot x="0" y="0" z="0" />
	<color r="0" g="102" b="255" />
	<reflection data="1" />
</cylinder>

</scene>

=== aanzieu/42-Raytracing/testfiles/abort.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "../dtd/norme.dtd">
<scene name="Test 1">
<mobius>
	<pos x="0" y="0" z="-0.500000" />
    <radius data="0.200000" />
    <color r="236" g="205" b="162" />
    <reflection data="0"/>
    <refraction data="0"/>
    <transparence data="0"/>
</mobius>
<plane>
	<origin x="0" y="-2" z="0" />
	<normal x="0" y="1" z="0" />
	<color r="123" g="123" b="200" />
	<reflection data="0" />
</plane>
<light>
	<pos x="-3" y="-2" z="-4" />
	<color r="255" g="255" b="255" />
	<intensity data="1" />
</light>
<light>
	<pos x="1" y="1" z="-3" />
	<color r="255" g="255" b="255" />
	<intensity data="1" />
</light>
<light>
	<pos x="-1" y="1" z="-3" />
	<color r="255" g="255" b="255" />
	<intensity data="1" />
</light>
<ambient>
	<color r="255" g="255" b="255" />
	<intensity data="0.1" />
</ambient>
<camera>
	<pos x="-2" y="2" z="-50" />
	<dir x="3" y="2" z="1" />
</camera>

</scene>

=== aanzieu/42-Raytracing/testfiles/sphere.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scene SYSTEM "../dtd/norme.dtd">
<scene name="One sphere">
<camera>
	<pos x="0" y="0" z="-10" />
	<dir x="0" y="0" z="1" />
	<rot x="0" y="0" z="0" />
	<tra x="0" y="0" z="0" />
</camera>
<ambient>
	<color r="255" g="255" b="255" a="1" />
	<intensity data="0.1" />
</ambient>
<light>
	<pos x="3" y="2" z="-4" />
	<color r="255" g="255" b="255" a="1" />
	<intensity data="1" />
</light>
<sphere>
	<pos x="0" y="0" z="1" />
	<radius data="0.4" />
	<tra x="0" y="0" z="0" />
	<color r="255" g="125" b="255" a="1" />
	<reflection data="0" />
</sphere>
</scene>
